spring:
  application:
    name: alumni-connect
  profiles:
    active: dev

server:
  port: 8080

logging:
  level:
    root: INFO
    io.github.adirajdev.alumniconnect: DEBUG
    org.hibernate.SQL: DEBUG